### ISSUE TITLE
Append a message to note

### ISSUE THREAD

**Issue by matttrach** [pimterry/notes#81]
Quickly append a message to a note without opening the file.

**Comment by pimterry** [comment]
Interesting idea! I'm open to this, but I'm not sure exactly what the CLI interface would be. Can you tell me a bit more about what you're imagining?

**Comment by matttrach** [comment]
something like `notes add <note name> "<message>"` 

so a note named 'thingList' that says:
```
List of things:
* A
* B
* C
```
You could add to it with: `notes add "thingList" '* D'`
and the note would look like this:
```
List of things:
* A
* B
* C
* D
```

**Comment by matttrach** [comment]
When I pair program we tend to have a lot of ideas that get lost to the ether, it would be nice to have something that I could call from the command line to quickly jot a note without losing the focus of what I am working on. Opening the file can be a bit cumbersome in that regard. I was thinking about adding notes in general as a function set within neovim. For instance if we have a meeting coming up and we have an idea for the meeting we could quickly add it to a list without losing context on what we are working on.

**Comment by pimterry** [comment]
Hi @matttrach, that makes sense thanks, I can see this use case. I think `append` would be better than `add` (which sounds a bit like it's creating a new note) but otherwise this sounds great.

Do you want to open a PR to add this? Take a look at https://github.com/pimterry/notes/pull/80/files if you'd like an example of how to add & test a new command.

**Comment by primis** [comment]
I created PR #85 which satisfies this issue ticket.
